# Generated by Django 3.0.5 on 2022-05-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_firstname', models.CharField(max_length=60)),
                ('Owner_lastname', models.CharField(max_length=60)),
                ('Owner_address', models.CharField(max_length=600)),
                ('Owner_email', models.CharField(max_length=100)),
                ('Owner_password', models.CharField(max_length=32)),
                ('Owner_dob', models.DateField()),
                ('Owner_mobileno', models.CharField(max_length=10)),
                ('Owner_gender', models.CharField(max_length=15)),
                ('Owner_license', models.ImageField(upload_to='img/Owner_License/')),
                ('Owner_agency', models.CharField(max_length=100)),
                ('Owner_city', models.CharField(max_length=30)),
                ('Owner_state', models.CharField(max_length=30)),
                ('Owner_country', models.CharField(max_length=30)),
                ('Owner_pincode', models.IntegerField()),
                ('isOwner', models.BooleanField(default=True)),
            ],
        ),
    ]
